---
- name: Capture OS info of all servers
  hosts: all
  tasks:
    - name: Capture OS name
      debug: 
        var: "{{ansible_distribution}}"
    - name: Capture OS version
      debug: 
        var: "{{ansible_distribution_version}}"
    - name: Capture OS version number
      debug:
        var: "{{ansible_distribution_major_version}}"      
...          

