---
- name: Create users and copying files into users home dir
  hosts: all 
  tasks: 
    - name: Create users
      user: 
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Venkataramana,b: venkataramana,c: /home/Venkataramana}
        - {a: Lakshmidevi,b: lakshmidevi,c: /tmp/Lakshmidevi}
    - name: Copy files into users home dirs
      copy: 
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items: 
        - {a: /etc/passwd,b: /home/Venkataramana}
        - {a: /etc/group,b: /tmp/Lakshmidevi}        
...          
             
