---
- name: Configure jenkins and required s/w's
  hosts: jenkinsserver
  tasks:
    - name: Install necessary s/w's
      apt: 
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items: 
        - {a: openjdk-11-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.440.1/jenkins.war
        dest: /home/ubuntu
- name: Configure tomcat on qa and prodserver
  hosts: servers
  tasks: 
    - name: Install tomcat9 and tomcat9-admin
      apt: 
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items: 
        - {a: tomcat9,b: present,c: yes}
        - {a: tomcat9-admin,b: present,c: no}
    - name: Copy customsied tomcat-user.xml file
      copy: 
        src: tomcat-user.xml 
        dest: /etc/tomcat9 
      notify: Restart tomcat
  handlers: 
    - name: Restart tomcat
      service:
        name: tomcat9
        state: restarted
...          
